// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ9szIKy_gu_tPBpeIwpb61oamDNe_COU',
    appId: '1:551233163781:web:50dadd318c2245b23a026c',
    messagingSenderId: '551233163781',
    projectId: 'touchsomegrass-abf11',
    authDomain: 'touchsomegrass-abf11.firebaseapp.com',
    storageBucket: 'touchsomegrass-abf11.firebasestorage.app',
    measurementId: 'G-14VHGB47DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk3bZFe2DlNTz-YiISEIo5yHkDsWhaL2g',
    appId: '1:551233163781:android:59355a43cc280c983a026c',
    messagingSenderId: '551233163781',
    projectId: 'touchsomegrass-abf11',
    storageBucket: 'touchsomegrass-abf11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiyMD7UNldC43OCr6RL7GrSS_kdOJ6NbQ',
    appId: '1:551233163781:ios:1a6970f23b0472bd3a026c',
    messagingSenderId: '551233163781',
    projectId: 'touchsomegrass-abf11',
    storageBucket: 'touchsomegrass-abf11.firebasestorage.app',
    iosBundleId: 'com.example.touchSomeGras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiyMD7UNldC43OCr6RL7GrSS_kdOJ6NbQ',
    appId: '1:551233163781:ios:1a6970f23b0472bd3a026c',
    messagingSenderId: '551233163781',
    projectId: 'touchsomegrass-abf11',
    storageBucket: 'touchsomegrass-abf11.firebasestorage.app',
    iosBundleId: 'com.example.touchSomeGras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ9szIKy_gu_tPBpeIwpb61oamDNe_COU',
    appId: '1:551233163781:web:cbb98ab7a3ed8fb63a026c',
    messagingSenderId: '551233163781',
    projectId: 'touchsomegrass-abf11',
    authDomain: 'touchsomegrass-abf11.firebaseapp.com',
    storageBucket: 'touchsomegrass-abf11.firebasestorage.app',
    measurementId: 'G-06YVC9TQWE',
  );
}
